workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ir.collaby
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Configure iOS code signing
        script: |
          xcode-project use-profiles

      - name: Build signed IPA (App Store)
        script: |
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  ios_ad_hoc:
    name: iOS Ad Hoc
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.ir.collaby
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Configure iOS code signing
        script: |
          xcode-project use-profiles

      - name: Build signed IPA
        script: |
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
