// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-_1jpgiiJVX2bMLqXwR5JS8qFoeNJnA',
    appId: '1:1015221394159:android:a5b2c944f56942672f191a',
    messagingSenderId: '1015221394159',
    projectId: 'collaby-app-4255f',
    storageBucket: 'collaby-app-4255f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOPIqKIpzzcM4PdJjyCaTTa7IPpgN_QRA',
    appId: '1:1015221394159:ios:6e53517453bcad732f191a',
    messagingSenderId: '1015221394159',
    projectId: 'collaby-app-4255f',
    storageBucket: 'collaby-app-4255f.firebasestorage.app',
    androidClientId: '1015221394159-dbkd90m6qa561hf3fjj5ccea8230cott.apps.googleusercontent.com',
    iosClientId: '1015221394159-pv3o7h45ttge9f1g1erks67ogp7qo20s.apps.googleusercontent.com',
    iosBundleId: 'com.ir.collaby',
  );

}